import { PlayerRoles } from '../player/player.types';

export const ROLES_BY_NUMBER_OF_PLAYERS: { [key: number]: PlayerRoles[] } = {
  5: [
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.MAFIA,
    PlayerRoles.DOCTOR,
  ],
  6: [
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.COMMISSAR,
    PlayerRoles.DOCTOR,
    PlayerRoles.GODFATHER,
  ],
  7: [
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.COMMISSAR,
    PlayerRoles.DOCTOR,
    PlayerRoles.MAFIA,
    PlayerRoles.GODFATHER,
  ],
  8: [
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.MAFIA,
    PlayerRoles.DOCTOR,
  ],
  9: [
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.MAFIA,
    PlayerRoles.DOCTOR,
  ],
  10: [
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.MAFIA,
    PlayerRoles.DOCTOR,
  ],
  11: [
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.MAFIA,
    PlayerRoles.DOCTOR,
  ],
  12: [
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.MAFIA,
    PlayerRoles.DOCTOR,
  ],
  13: [
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.MAFIA,
    PlayerRoles.DOCTOR,
  ],
  14: [
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.MAFIA,
    PlayerRoles.DOCTOR,
  ],
  15: [
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.MAFIA,
    PlayerRoles.DOCTOR,
  ],
  16: [
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.MAFIA,
    PlayerRoles.DOCTOR,
  ],
  17: [
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.MAFIA,
    PlayerRoles.DOCTOR,
  ],
  18: [
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.MAFIA,
    PlayerRoles.DOCTOR,
  ],
  19: [
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.PEACEFUL_RESIDENT,
    PlayerRoles.MAFIA,
    PlayerRoles.DOCTOR,
  ],
};